apiVersion: v1
kind: Service
metadata:
  name: web-hello-k8s-nginx
spec:
  type: LoadBalancer
  selector:
    app: web-hello-k8s-nginx
  ports:
  - port: 8080
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-hello-k8s-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-hello-k8s-nginx
  template:
    metadata:
      labels:
        app: web-hello-k8s-nginx
    spec:
      containers:
      - name: web-hello-k8s-nginx
        image: saiprasadmohandas/web-hello-k8s-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
